name: Deploy Windows

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    uses: giocaizzi/python-dev-actions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
        os: "windows-latest"
        python-version: "3.10"
        python-tested-versions: "['3.9','3.10','3.11','3.12']"
        python-build-backend: "poetry"
